name: updating-sivep-data
on:
  push:
    branches: main
  schedule:
    - cron: "05 22 * * 3"

jobs:
  run:
    runs-on: [macOS-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1' # The R version to download (if necessary) and use.
      - run: Rscript -e 'print(paste0("Updating data at", as.Date(Sys.time())))'
      - name: Install packages
        run: Rscript -e 'install.packages(c("tidyverse", "zoo", "here", "data.table", "httr", "gtsummary", "broom", "vroom", "arrow"))'
      - name: Run script 
        run: Rscript -e 'source(here::here("code", "App Data Preparation Functions", "app_update_sivep.R"))'
      - name: Commit results
        run:  |
          git pull
          git push
          git add .
          git commit -m "updating sivep data `date +'%Y-%m-%d %H:%M:%S'`" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
